#You don't need to edit it.
version: 2.0.0

#Enabled: 'Chinese','English'
lang: 'English'

#Enabled: 'Disable','ChatBox','SubTitle','ActionBar'
damage_visible_mode: ActionBar

#Enabled: 'edge','pc'
#'edge': means using edge(weight) to decide which dragon(including default dragon) to spawn.
#'pc': namely 'priority+chance', dragons(except the default one) will be sorted in descending order of priority, and plugin will sequently try to spawn each dragon(according to respective chance). Once succeed, it will spawn and dragons behind it will be skipped. If all attempts fail, spawn the default one.
special_dragon_jude_mode: 'edge'

#format: 'name:edge'
#this name is corresponding to the file name
#For example,if you want to add a new dragon, you can create a new file named '<NAME>.yml' in plugins/EnderDragon/setting, and then add - '<NAME>:<EDGE>' to 'dragon_setting_file'
dragon_setting_file:
  - 'default:5'
  - 'special:5'

auto_respawn:
  enable: false
  world_the_end_name: world_the_end
  #some examples:
  # minute:30            -> respawn every 30 minutes
  # hour:4               -> respawn every 4 hours
  # day:1,00:00          -> respawn at 00:00 every day
  # day:10,14:30         -> respawn at 14:30 every 10 days
  # week:6,22:00         -> respawn at 22:00 every Saturday(the 6th day of one week)
  # week:7,09:00         -> respawn at 09:00 every Sunday
  # month:8,11:43        -> respawn at 11:43,the 8th day every month
  # year:200,00:00       -> respawn at 00:00,the 200th day every year
  respawn_time: 'day:10,22:00'
  #whether player(in survival mode) can break the end_crystal when respawn phase is running
  invulnerable: false

#if set this to true, end_crystal can still be crafted or placed,but end_crystal that placed by player cannot respawn the ender_dragon
resist_player_respawn: false
#if set this to true, player cannot gather dragon_breath with glass_bottle
resist_dragon_breath_gather: false
#The gui that will be shown when using "/ed drop gui"
main_gui: main