#配置文件版本，请勿修改
version: 1.8.2

#普通末影龙
normal-dragon:
  name: '末影龙'

  #被末影水晶治疗时，末影龙每秒的回血量(原版末影龙每秒回复2点生命)
  crystal-heal: 2.0

#特殊末影龙
special-dragon:
  name: '特殊末影龙'

  #每几次有概率复活出特殊的末影龙
  #千万不要设置该项为0！！！！！否则会引发报错
  #如果不希望复活出特殊末影龙，请设置下方的概率为0
  respawn-circle: 10

  #生成特殊末影龙的概率，请填入0-100的整数(单位：%)
  chance: 100

  #生成特殊龙后全服提醒
  spawn-remind: true

  #若设置为false代表普通末影龙死亡也会全服播报
  #若设置为true代表仅特殊末影龙死亡会全服播报
  only-special-death-remind: false

  #特殊末影龙最大血量
  #请填入大于0的数字，否则会按原版末影龙血量生成
  #示例：“100”、“1000.0”、“200.00”
  #TIPS：原版末影龙血量为200
  max-health: 400

  #特殊末影龙生成时血量
  #请填入大于0的数字，否则会按特殊末影龙最大血量生成
  #请勿设置此值大于特殊龙最大血量(max-health)
  spawn-health: 200

  #特殊龙对玩家伤害倍数
  #请输入大于0的数字，否则会按原版末影龙伤害计算
  #示例：“0.8”、“1.25”、“3”
  damage-multiply: 1.0

  #特殊龙攻击玩家对玩家造成的药水效果
  #请严格安装'药水效果 持续时间 药水等级'的格式
  #持续时间请填入大于0的整数(单位：秒)
  #药水等级取值1-256的整数，输入1即代表1级，与effect指令不同！
  attack-effect:
    - 'wither 10 1'
    - 'hunger 60 1'
    - 'weakness 30 2'

  #特殊末影龙掉落经验值
  #TIPS：原版第一次击杀末影龙掉落12000经验，此后每一次击杀掉落500经验(请填入整数)
  exp-drop: 12000

  #龙蛋生成设置
  dragon-egg-spawn:

    #生成龙蛋概率
    #请填入0-100的整数(单位：%)
    #填入0代表不生成龙蛋
    chance: 100

    #生成龙蛋延迟
    #末影龙死后多少时间生成龙蛋(单位：游戏刻，20游戏刻=1秒)
    #填入大于或等于0的整数
    #末影龙死后大约20秒(400游戏刻)后末地传送门生成，因此加一个延迟可以形成龙蛋和传送门几乎一起出现的效果
    #此外，如果在龙蛋生成前玩家在下方放了火把，床之类的方块，龙蛋下落后会直接形成掉落物回主世界，加一个延迟可以减少不必要的麻烦
    delay: 410

    #龙蛋生成坐标(末地)
    #y轴设置70一般没问题，想精确的话请依照自己服务器情况而定
    x: 0
    y: 70
    z: 0

  #特殊龙发光的颜色
  #若要关闭发光功能，设置该项为“disable”
  #所有可用颜色如下(不区分大小写)
  #AQUA-青色，BLACK-黑色，BLUE-蓝色，DARK_AQUA-深青，DARK_BLUE-深蓝，DARK_GRAY-深灰，DARK_GREEN-深绿，DARK_PURPLE-深紫，DARK_RED-深红，GOLD-金色，GRAY-灰色，GREEN-绿色，LIGHT_PURPLE-紫色，RED-红色，WHITE-白色，YELLOW-黄色
  glow-color: GOLD

  #玩家攻击末影龙时伤害显示
  #填入0代表不显示
  #填入1代表显示在副标题栏(会有略微视野遮挡)
  #输入2代表显示在聊天栏(可能会刷屏)
  #输入3代表显示在ActionBar(推荐)
  damage-visible: 3

  #指令/ed drop gui 打开的页面的标题
  drop-gui-title: '§b特殊龙掉落物§r'

  #被末影水晶治疗时，特殊龙每秒的回血量(原版末影龙被水晶治疗时每秒回复2点生命)
  crystal-heal: 5.0

  #特殊龙对其他生物造成伤害后吸血
  #吸血量=伤害*吸血率(自动按百分数计算)+基础吸血量
  suck-blood:
    enable: true

    #设置为true时，特殊龙攻击其他生物时不吸血
    only-player: true

    #吸血率(单位：%)
    rate: 50

    #基础吸血量
    base-suck-blood: 10

command:
  #是否启用在以下生物死亡后执行特定指令
  #以下指令均可用%player%代表击杀末影龙的玩家的名字
  #如果玩家从未造成过有效攻击(比如一直用床炸而从未亲自攻击)，涉及%player%的这条指令将被忽略
  #举例：- 'give %player% diamond 1'
  enable: false

  #普通末影龙
  normal-dragon:
    - ''
    - ''
    - ''
  #特殊龙
  special-dragon:
    - ''
    - ''
    - ''