name: EnderDragon
version: 2.0.0
main: xanadu.enderdragon.EnderDragon
author: Xanadu13
api-version: 1.13
softdepend:
  - MythicLib
  - MMOItems
commands:
  enderdragon:
    description: 'Plugin main command'
    aliases: [ed]
    permission: ''
    permission-message: "ยง4I'm Sorry,but you do not have permission to do that."
permissions:
  ed.reload:
    description: 'Reload the config'
    default: op
  ed.drop.edit:
    description: 'Edit the drop_item of dragons'
    default: op
  ed.drop.gui:
    description: 'Preview the drop_item of dragons'
    default: true
  ed.respawn:
    description: 'Respawn a new dragon'
    default: op
  ed.update:
    description: 'Update the config file'
    default: op